package:
    name: daetk
    version: 1.0.0

source:
    fn: daetk-1.0.0.tar.gz
    url: https://github.com/erdc-cm/daetk/archive/1.0.0.tar.gz
    sha256: 31951dd1f7a7f92c27a186b45bf0e0d12d9ce28d9c2d9fa4f2e35a3579985ed5

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - petsc 3.7*
    - parmetis 4.0*
    - mpich 3*

  run:
    - petsc 3.7*
    - parmetis 4.0*
    - mpich 3*

about:
    home: https://github.com/erdc-cm/daetk
    summary: The Differential Algebraic Equation Toolkit
