{% set version = "4.5.4" %}

{% set variant = "openblas" %}

{% set dyn_ext = ".so" %}  # [linux]
{% set dyn_ext = ".dylib" %}  # [osx]
{% set dyn_ext = ".dll" %}  # [win]


package:
  name: suitesparse
  version: {{ version }}

source:
  fn: SuiteSparse-{{ version }}.tar.gz
  url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-{{ version }}.tar.gz
  sha256: 698b5c455645bb1ad29a185f0d52025f3bd7cb7261e182c8878b0eb60567a714

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - openblas 0.2.19|0.2.19.*
    - tbb
    - cmake
    - metis 5.1.*

  run:
    - openblas 0.2.19|0.2.19.*
    - tbb
    - metis 5.1.*

test:
  commands:
    - test -f ${PREFIX}/lib/libamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libbtf{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libccolamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcholmod{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcolamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcxsparse{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libklu{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libldl{{ dyn_ext }}
    - test -f ${PREFIX}/lib/librbio{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libspqr{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libsuitesparseconfig{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libumfpack{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libamd.a
    - test -f ${PREFIX}/lib/libbtf.a
    - test -f ${PREFIX}/lib/libcamd.a
    - test -f ${PREFIX}/lib/libccolamd.a
    - test -f ${PREFIX}/lib/libcholmod.a
    - test -f ${PREFIX}/lib/libcolamd.a
    - test -f ${PREFIX}/lib/libcxsparse.a
    - test -f ${PREFIX}/lib/libklu.a
    - test -f ${PREFIX}/lib/libldl.a
    - test -f ${PREFIX}/lib/librbio.a
    - test -f ${PREFIX}/lib/libspqr.a
    - test -f ${PREFIX}/lib/libsuitesparseconfig.a
    - test -f ${PREFIX}/lib/libumfpack.a

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
  summary: A suite of sparse matrix algorithms
