{% set version = "5.2.1" %}

package:
    name: superlu
    version: {{ version }}

source:
    fn: superlu-{{ version }}.tar.gz
    url: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_{{ version }}.tar.gz
    sha256: 28fb66d6107ee66248d5cf508c79de03d0621852a0ddeba7301801d3d859f463

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - openblas 0.2.19|0.2.19.*
    - cmake
  run:
    - openblas 0.2.19|0.2.19.*

test:
  commands:
    - test -f ${PREFIX}/lib/libsuperlu.a

about:
    home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
    license: BSD 3-clause
    summary: |
      Supernodal LU: solvers for large, sparse, nonsymmetric systems of linear
      equations.
