{% set build = 0 %}
{% set version = '3.7.4' %}
{% set sha256 = '92aab64b7fd9c8491eefffd4ccebe5c8a0ba90a464e766db453e8fe96fd332e9' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set openblas_version = '0.2.19' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: petsc
  version: {{version}}

source:
  fn: petsc-lite-{{version}}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: {{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - python 2.7.*
    - cmake
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - metis 5.*
    - parmetis 4.0.*
    - suitesparse 4.5.4
    - superlu_dist 5.*
  run:
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - metis 5.*
    - parmetis 4.0.*
    - suitesparse 4.5.4
    - superlu_dist 5.*

test:
  source_files:
    - src/snes/examples/tests

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
