package:
  name: superlu_dist
  version: 5.1.3

source:
  fn: superlu_dist_5.1.3.tar.gz
  url: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_5.1.3.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake >=2.8.12
    - gcc      # [osx]
    - openblas # [unix]
    - parmetis 4.0.3*
  run:
    - libgcc   # [osx]
    - openblas # [unix]
    - parmetis 4.0.3*

about:
  home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
  license: University of California
  summary: SuperLU is a general purpose library for the direct solution of large, sparse, nonsymmetric systems of linear equations on high performance machines.
