{% set name = "metis" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/{{ name }}-{{ version }}.tar.gz
  sha256: 76faebe03f6c963127dbb73c13eab58c9a3faeae48779f049066a21c087c5db2
  patches:
    - vc14.patch

build:
  number: 0 
  binary_relocation: true
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - cmake
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    - graphchk  # [unix]
    - cmpfillin -h  # [unix]
    - mpmetis -h  # [unix]
    - gpmetis -h  # [unix]
    - ndmetis -h  # [unix]
    - gpmetis -h  # [unix]
    - m2gmetis -h  # [unix]
    - test -f $PREFIX/include/metis.h  # [unix]
    - test -f $PREFIX/lib/libmetis.dylib  # [osx]
    - test -f $PREFIX/lib/libmetis.so  # [linux]
    - if not exist "%LIBRARY_LIB%\\metis.lib" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\graphchk.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\cmpfillin.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\mpmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\gpmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\ndmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\gpmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\m2gmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\metis.h" exit 1  # [win]
  source_files:
    - graphs/metis.mesh
    - graphs/mdual.graph
    - graphs/mdual.graph
    - graphs/test.mgraph
    - graphs/metis.mesh

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'METIS - Serial Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    METIS is a set of serial programs for partitioning graphs, partitioning 
    finite element meshes, and producing fill reducing orderings for sparse 
    matrices. The algorithms implemented in METIS are based on the multilevel 
    recursive-bisection, multilevel k-way, and multi-constraint partitioning 
    schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/metis/metis/faq
